# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 #pegar a versao mais atulizada do codigo

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with: 
          node-version: 14.x #versao LTS
        
        #cache para o yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: | 
          ${{ runner.os }}-yarn-
        
        #Instalar as dependencias Yarn/NPM
      - name: Install dependecies
        run: yarn
      
      #Executar a build
      - name: Run bulid
        run: yarn build
        
        
      #Copiar a pasta dist para dentro da digitalOcean para mandar os arquivos atualizados
      - name: copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules" #copiar tudo
          target: "~/app/GoBarber-Bootcamp" #colar na pasta


#Executar "yarn" na Digital Ocean
#Executar as migrations do TypeORM
#Restart no servidor Node,js para pegar as novas alterações
